### ISSUE TITLE
Is it possible to avoid specification of protocol twice?

### ISSUE THREAD

**Issue by BlaineEXE** [kubernetes-sigs/container-object-storage-interface-api#24]
https://github.com/kubernetes-sigs/container-object-storage-interface-api/blob/7c26b4fc1ed9e719cd3342f2666c855260930cc9/apis/objectstorage.k8s.io/v1alpha1/protocol_types.go#L28-L37

Do we need to include `Name` as well as the different protocol options? This makes it so that whenever options are included, users must specify their choice twice: once in `Name` and once implicitly in the protocol spec. E.g.,
```yaml
protocol:
  name: s3
  s3:
     blah: stuff
``` 

K8s volume claims use a syntax where the option itself implicitly specifies the option desired. E.g.,
```yaml
volumes:
  - name: myDir
    emptyDir: {}
```

Does it make sense to follow that pattern for the protocol also? Like below would be an S3 config with no options set.
```yaml
protocol:
  s3: {}
```

**Comment by jeffvance** [comment]
Good observation @BlaineEXE 
cc @wlan0

**Comment by wlan0** [comment]
@BlaineEXE without the name, we wouldn't be able to disambiguate between no options and default options. In case of pvc, the emptyDir you've specified is interpreted as a nil value. It only works because emptyDir is the default volume type (https://github.com/kubernetes/api/blob/master/core/v1/types.go#L43). This would give you the same result

```
volume:
  - name: myDir
```

In case of protocol, we cannot assume a default like that.

**Comment by BlaineEXE** [comment]
I don't believe that is quite correct. I did an experiment in Rook with the Protocol. 

I think the secret is to set the `nullable: true` field in the CRD spec so that if the value is not present, it gets a nil pointer. 

I added the below CRD spec to Rook and types for the protocols to test.

```yaml
                protocol:
                  properties:
                    azureBlob:
                      properties:
                        containerName:
                          type: string
                        storageAccount:
                          type: string
                      type: object
                      nullable: true
                    gcs:
                      properties:
                        bucketName:
                          type: string
                        privateKeyName:
                          type: string
                        projectID:
                          type: string
                        serviceAccount:
                          type: string
                      type: object
                      nullable: true
                    s3:
                      properties:
                        bucketName:
                          type: string
                        endpoint:
                          type: string
                        region:
                          type: string
                        signatureVersion:
                          enum:
                          - s3v2
                          - s3v4
                          type: string
                      type: object
                      nullable: true
                  type: object
```

I put nothing in the manifest to get nil specs for all. (golang print `"%+v"` for the protocol shown after examples)
```
{S3:<nil> AzureBlob:<nil> GCS:<nil>}
```

I put this in the manifest to get a non-nil S3 spec.
```yaml
  protocol:
    s3: {}
```
```
{S3:0xc000d29600 AzureBlob:<nil> GCS:<nil>}
```

This should allow testing for non-nil to see if anything is present, even if nothing is actually specified.
